### PR TITLE
VULCAN-100 Rename vulcan to apio.architect

### PR DESCRIPTION
**Pull request by ahdezma**

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
👏

**Comment by ahdezma** [comment]
SF is failing because the modules that were previously in the exceptions are no longer there. I don't know what can we do about it https://github.com/liferay/liferay-portal/blob/f9d7abddf4b8987e48c3143bc1d8f7acf519a0a7/modules/util/source-formatter/src/main/resources/sourcechecks.xml#L151

I want to refactor those two modules into "api" modules, but I don't have the time right now to do it. We need this change to be made ASAP.

The other SF failure is because the main folder in central is "vulcan" and should be renamed to "apio-architect". @hhuijser 

We talk about moving it out of foundation, as a separated app, so we can have our own release cycle. Can this two things be made simultaneously? @JorgeFerrer @stsquared99

**Comment by hhuijser** [comment]
@mtambara, can you help out with this? Thanks!

**Comment by mtambara** [comment]
@ahdezma @hhuijser Changing https://github.com/liferay/liferay-portal/blob/f9d7abddf4b8987e48c3143bc1d8f7acf519a0a7/modules/util/source-formatter/src/main/resources/sourcechecks.xml#L151 to add "apio-architect-liferay-portal" to the exceptions should fix it. First, send a pull to add all the new apio architect modules to the exceptions list before they are actually added, then after all the vulcan modules have been renamed, send another pull to remove the old vulcan modules from the list.

**Comment by nhpatt** [comment]
Done here: https://github.com/brianchandotcom/liferay-portal/pull/53442 . I'll launch CI again when that PR passes.

But the violations with "Module 'apio-architect-message-json-plain' should start with 'vulcan'" should still be failing, right?

**Comment by mtambara** [comment]
@nhpatt Yeah, that change will only fix the "Exporting packages" sf failure

**Comment by nhpatt** [comment]
ci:retest

**Comment by ahdezma** [comment]
ci:retest

**Pull request merged**
