### PR TITLE
VULCAN-76

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@ahdezma fyi

**Comment by nhpatt** [comment]
ci:retest

**Comment by ahdezma** [comment]
ci:retest

**Comment by ahdezma** [comment]
There were some problems with SF. Pulled and updated with the fix for those problems here: https://github.com/liferay/com-liferay-vulcan/pull/55

Thanks :)

**Pull request closed without merging**
